# Generated by Django 3.2.9 on 2021-12-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='display_order',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
