# Generated by Django 3.2.9 on 2021-11-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(help_text='图片尺寸3840*800', null=True, upload_to='banner', verbose_name='轮播图'),
        ),
    ]
